github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/upornia-downloader",
  "https://serp.co/products/upornia-downloader/reviews/",
  "https://extensions.serp.co/upornia-downloader",
  "https://browserextensions.io/upornia-downloader"
]
